export const metadata = {
  title: "next.js",
  description: "Generated by next.js",
};

import HydrationErrorSuppressor from "@/components/HydrationErrorSuppressor";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <HydrationErrorSuppressor />
        {children}
      </body>
    </html>
  );
}
