/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type DeliveryPricingConfig = {
  _id: string;
  _type: "deliveryPricingConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  zones?: Array<{
    id?: string;
    name?: string;
    basePrice?: number;
    color?: string;
    active?: boolean;
    coordinates?: Array<{
      lat?: number;
      lng?: number;
      _key: string;
    }>;
    _key: string;
  }>;
  demand?: {
    level?: "low" | "medium" | "high" | "custom";
    multiplier?: number;
  };
  scheduleRules?: Array<{
    id?: string;
    name?: string;
    startTime?: string;
    endTime?: string;
    multiplier?: number;
    active?: boolean;
    _key: string;
  }>;
  outsideZone?: {
    mode?: "reject" | "special_fee";
    specialFee?: number;
  };
  debug?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type StoreCategory = {
  _id: string;
  _type: "storeCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  icon?: {
    type?: "emoji" | "image";
    emoji?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LegalAcceptance = {
  _id: string;
  _type: "legalAcceptance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  documentType?: string;
  documentVersion?: string;
  acceptedAt?: string;
  userId?: string;
  role?: string;
  acceptanceSource?: string;
  ipHashOrLimitedIp?: string;
  userAgentSummary?: string;
};

export type AffiliateStoreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "affiliateStore";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type SaleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sale";
};

export type PromoBanner = {
  _id: string;
  _type: "promoBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  bannerType?:
    "promotion" | "announcement" | "info" | "featured" | "warning" | "event";
  mainColor?:
    | "#FFFFFF"
    | "#000000"
    | "#09193B"
    | "#850C22"
    | "#111827"
    | "#166534"
    | "#0F766E"
    | "#6D28D9"
    | "#C2410C";
  desktopImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  affiliateStore?: AffiliateStoreReference;
  product?: ProductReference;
  sortOrder?: number;
  displayDurationSeconds?: number;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
  ctaText?: string;
  ctaLink?: string;
  sale?: SaleReference;
};

export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  discountType?: "fixed_amount" | "percentage";
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  stripePromotionCodeId?: string;
  autoApply?: boolean;
  allowedOrderTypes?: Array<string>;
  allowedPaymentMethods?: Array<string>;
  allowedStores?: Array<
    {
      _key: string;
    } & AffiliateStoreReference
  >;
  isActive?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type RepartidorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "repartidor";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  baserowRowId?: number;
  baserowSyncStatus?: string;
  baserowSyncedAt?: string;
  baserowSyncError?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  phone?: string;
  orderType?: "delivery" | "pickup";
  paymentMethod?:
    | "stripe"
    | "cash_on_delivery"
    | "cash_at_store"
    | "card_at_store"
    | "manual"
    | "bank_transfer"
    | "oxxo"
    | "card"
    | "cash_on_pickup"
    | "card_on_pickup";
  paymentProvider?: "stripe" | "cash" | "external_pos" | "none";
  paidOnline?: boolean;
  requiresStripeReconciliation?: boolean;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    customizations?: Array<{
      title?: string;
      options?: Array<{
        label?: string;
        priceDelta?: number;
        _key: string;
      }>;
      _key: string;
    }>;
    notes?: string;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?:
    | "pending"
    | "paid"
    | "failed"
    | "expired"
    | "pending_delivery"
    | "pending_pickup"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "ready_for_pickup"
    | "picked_up"
    | "completed";
  orderStatus?:
    | "pending"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "ready_for_pickup"
    | "picked_up"
    | "completed";
  paymentStatus?:
    | "pending"
    | "paid"
    | "failed"
    | "expired"
    | "unpaid"
    | "refunded"
    | "requires_refund";
  expiredAt?: string;
  paidAt?: string;
  bankTransferReference?: string;
  bankTransferClabe?: string;
  oxxoReference?: string;
  orderDate?: string;
  fulfillmentProvider?:
    | "pickup"
    | "restaurant_delivery"
    | "elmenu_delivery"
    | "third_party_logistics";
  sellerType?: string;
  sellerId?: string;
  sellerSnapshot?: {
    id?: string;
    name?: string;
    address?: string;
  };
  fulfillmentProviderSnapshot?: {
    provider?: string;
    restaurantName?: string;
  };
  legalTermsVersion?: string;
  privacyVersion?: string;
  cancellationPolicyVersion?: string;
  deliveryPinHash?: string;
  deliveryPinCiphertext?: string;
  deliveryPinCreatedAt?: string;
  deliveryPinExpiresAt?: string;
  deliveryPinVerifiedAt?: string;
  deliveryPinVerifiedBy?: string;
  deliveryPinAttemptCount?: number;
  deliveryPinLockedUntil?: string;
  deliveryVerificationMethod?:
    "pin" | "customer_confirmation" | "support_override" | "not_required";
  deliveryVerificationStatus?:
    "pending" | "verified" | "locked" | "overridden" | "not_required";
  deliveryVerificationEvidence?: string;
  authorizedRecipientName?: string;
  authorizedRecipientRelation?: string;
  authorizedThirdPartyDelivery?: boolean;
  refundStatus?:
    | "not_requested"
    | "requested"
    | "under_review"
    | "approved"
    | "partially_approved"
    | "rejected"
    | "processing"
    | "refunded"
    | "failed";
  refundRequestedAt?: string;
  refundRequestedBy?: string;
  refundReason?: string;
  refundAmount?: number;
  refundResolution?: string;
  refundResolvedAt?: string;
  refundResolvedBy?: string;
  stripeRefundId?: string;
  refundEvidence?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  subtotal?: number;
  shippingCost?: number;
  productsSubtotal?: number;
  shippingFee?: number;
  discount?: number;
  tax?: number;
  platformCommission?: number;
  stripeFee?: number;
  stripeNetAmount?: number;
  driverPayout?: number;
  grossTotal?: number;
  storeNetTotal?: number;
  platformNetTotal?: number;
  shippingAddress?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
  };
  codInstructions?: string;
  deliveryNotes?: string;
  repartidorAsignado?: RepartidorReference;
  repartidorAsignadoAt?: string;
  deliveryOfertaEnviada?: boolean;
  deliveryOfertaExpiresAt?: string;
  dispatchStatus?:
    | "not_required"
    | "waiting_for_driver"
    | "offered"
    | "accepted"
    | "at_door"
    | "completed";
  settlementStatus?: "pending" | "ready" | "settled" | "cancelled" | "refunded";
  cashCollectedBy?:
    "store" | "community_driver" | "store_driver" | "admin" | "none";
  driverType?: "store" | "community" | "none";
  offeredTo?: RepartidorReference;
  pickupStore?: AffiliateStoreReference;
  estimatedPickupDate?: string;
  pickupStatus?: "in_transit" | "ready_for_pickup" | "picked_up" | "expired";
  pickupCode?: string;
  affiliateStore?: AffiliateStoreReference;
  cancelledAt?: string;
  refundedAt?: string;
  settlementDate?: string;
  orderEvents?: Array<{
    type?: string;
    at?: string;
    actor?: string;
    source?: string;
    reason?: string;
    payloadJson?: string;
    _key: string;
  }>;
};

export type OrderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "order";
};

export type Repartidor = {
  _id: string;
  _type: "repartidor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre?: string;
  telefono?: string;
  tiendaAsignada?: AffiliateStoreReference;
  activo?: boolean;
  disponible?: boolean;
  disponibleDesde?: string;
  disponibleHasta?: string;
  duracionDisponibilidadMinutos?: number;
  estadoDisponibilidad?: "available" | "offline" | "busy" | "offer_pending";
  ultimaActividad?: string;
  pendienteConfirmacion?: boolean;
  confirmacionEnviadaAt?: string;
  esperandoSeleccionDisponibilidad?: boolean;
  extensionPendiente?: boolean;
  extensionPreguntadaAt?: string;
  autoDesconectadoAt?: string;
  motivoDesconexion?: string;
  ultimoPedidoOfertado?: OrderReference;
  ofertaTipo?: "single" | "bundle";
  pedidosOfertados?: Array<
    {
      _key: string;
    } & OrderReference
  >;
  restauranteOferta?: AffiliateStoreReference;
  ofertaEnviadaAt?: string;
  ofertaExpiraAt?: string;
  notas?: string;
};

export type StoreUpdateRequest = {
  _id: string;
  _type: "storeUpdateRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  store?: AffiliateStoreReference;
  changes?: {
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    coverImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    isOpen?: boolean;
    highDemandMode?: boolean;
    contact?: {
      phone?: string;
      email?: string;
      manager?: string;
    };
    operatingHours?: {
      monday?: string;
      tuesday?: string;
      wednesday?: string;
      thursday?: string;
      friday?: string;
      saturday?: string;
      sunday?: string;
    };
    serviceTypes?: {
      delivery?: boolean;
      pickup?: boolean;
      deliveryRadius?: number;
      onDemand?: boolean;
      onDemandExtraMinutes?: number;
      minimumOrderDelivery?: number;
    };
    address?: {
      street?: string;
      city?: string;
      state?: string;
      postalCode?: string;
      country?: string;
    };
  };
  status?: "pending" | "approved" | "rejected";
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ProductUpdateRequest = {
  _id: string;
  _type: "productUpdateRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  changes?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<
      {
        _key: string;
      } & OptionGroup
    >;
  };
  status?: "pending" | "approved" | "rejected";
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type OptionGroup = {
  _type: "optionGroup";
  title?: string;
  description?: string;
  required?: boolean;
  selectionType?: string;
  options?: Array<
    {
      _key: string;
    } & Option
  >;
};

export type Option = {
  _type: "option";
  label?: string;
  description?: string;
  priceDelta?: number;
  isDefault?: boolean;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  affiliateStore?: AffiliateStoreReference;
  optionGroups?: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "single" | "multiple";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }>;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  approvalStatus?: "pending" | "approved" | "rejected";
  isVisible?: boolean;
  pendingChanges?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<{
      title?: string;
      description?: string;
      required?: boolean;
      selectionType?: string;
      options?: Array<{
        label?: string;
        description?: string;
        priceDelta?: number;
        isDefault?: boolean;
        _type: "option";
        _key: string;
      }>;
      _type: "optionGroup";
      _key: string;
    }>;
  };
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
};

export type StoreCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "storeCategory";
};

export type AffiliateStore = {
  _id: string;
  _type: "affiliateStore";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ownerClerkUserId?: string;
  name?: string;
  storeCategories?: Array<
    {
      _key: string;
    } & StoreCategoryReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  storeId?: string;
  categories?: Array<{
    name?: string;
    slug?: Slug;
    order?: number;
    _key: string;
  }>;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  coordinates?: {
    latitude?: number;
    longitude?: number;
  };
  contact?: {
    phone?: string;
    email?: string;
    manager?: string;
  };
  operatingHours?: {
    monday?: string;
    tuesday?: string;
    wednesday?: string;
    thursday?: string;
    friday?: string;
    saturday?: string;
    sunday?: string;
  };
  isActive?: boolean;
  isOpen?: boolean;
  manualOperationalStatus?: "auto" | "open" | "closed";
  highDemandMode?: boolean;
  hasOwnDelivery?: boolean;
  capacity?: number;
  averageDeliveryTime?: number;
  deliveryFee?: number;
  deliveryTimeMin?: number;
  deliveryTimeMax?: number;
  serviceTypes?: {
    delivery?: boolean;
    pickup?: boolean;
    deliveryRadius?: number;
    minimumOrderDelivery?: number;
    onDemand?: boolean;
    onDemandExtraMinutes?: number;
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | DeliveryPricingConfig
  | SanityImageAssetReference
  | StoreCategory
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | LegalAcceptance
  | AffiliateStoreReference
  | ProductReference
  | SaleReference
  | PromoBanner
  | Sale
  | SanityFileAssetReference
  | RepartidorReference
  | Order
  | OrderReference
  | Repartidor
  | StoreUpdateRequest
  | CategoryReference
  | ProductUpdateRequest
  | BlockContent
  | OptionGroup
  | Option
  | Product
  | StoreCategoryReference
  | AffiliateStore
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/orders/getMyOrders.tsx
// Variable: MY_ORDERS_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {      ...,      "isClickCollect": orderType == "pickup",      "storeInfo": select(        orderType == "pickup" => {          "storeName": pickupStore->name,          "storeAddress": pickupStore->address.street,          "storePhone": pickupStore->contact.phone        }      ),      products[]{        ...,        product->      }    }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  baserowRowId?: number;
  baserowSyncStatus?: string;
  baserowSyncedAt?: string;
  baserowSyncError?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  phone?: string;
  orderType?: "delivery" | "pickup";
  paymentMethod?:
    | "bank_transfer"
    | "card_at_store"
    | "card_on_pickup"
    | "card"
    | "cash_at_store"
    | "cash_on_delivery"
    | "cash_on_pickup"
    | "manual"
    | "oxxo"
    | "stripe";
  paymentProvider?: "cash" | "external_pos" | "none" | "stripe";
  paidOnline?: boolean;
  requiresStripeReconciliation?: boolean;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      affiliateStore?: AffiliateStoreReference;
      optionGroups?: Array<{
        title?: string;
        description?: string;
        required?: boolean;
        selectionType?: "multiple" | "single";
        options?: Array<{
          label?: string;
          description?: string;
          priceDelta?: number;
          isDefault?: boolean;
          _type: "option";
          _key: string;
        }>;
        _type: "optionGroup";
        _key: string;
      }>;
      slug?: Slug;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      description?: BlockContent;
      price?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      approvalStatus?: "approved" | "pending" | "rejected";
      isVisible?: boolean;
      pendingChanges?: {
        name?: string;
        price?: number;
        stock?: number;
        description?: BlockContent;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        categories?: Array<
          {
            _key: string;
          } & CategoryReference
        >;
        optionGroups?: Array<{
          title?: string;
          description?: string;
          required?: boolean;
          selectionType?: string;
          options?: Array<{
            label?: string;
            description?: string;
            priceDelta?: number;
            isDefault?: boolean;
            _type: "option";
            _key: string;
          }>;
          _type: "optionGroup";
          _key: string;
        }>;
      };
      submittedBy?: string;
      submittedAt?: string;
      approvedBy?: string;
      approvedAt?: string;
      rejectedBy?: string;
      rejectedAt?: string;
      rejectionReason?: string;
    } | null;
    quantity?: number;
    customizations?: Array<{
      title?: string;
      options?: Array<{
        label?: string;
        priceDelta?: number;
        _key: string;
      }>;
      _key: string;
    }>;
    notes?: string;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?:
    | "cancelled"
    | "completed"
    | "delivered"
    | "expired"
    | "failed"
    | "paid"
    | "pending_delivery"
    | "pending_pickup"
    | "pending"
    | "picked_up"
    | "ready_for_pickup"
    | "shipped";
  orderStatus?:
    | "cancelled"
    | "completed"
    | "delivered"
    | "pending"
    | "picked_up"
    | "processing"
    | "ready_for_pickup"
    | "shipped";
  paymentStatus?:
    | "expired"
    | "failed"
    | "paid"
    | "pending"
    | "refunded"
    | "requires_refund"
    | "unpaid";
  expiredAt?: string;
  paidAt?: string;
  bankTransferReference?: string;
  bankTransferClabe?: string;
  oxxoReference?: string;
  orderDate?: string;
  fulfillmentProvider?:
    | "elmenu_delivery"
    | "pickup"
    | "restaurant_delivery"
    | "third_party_logistics";
  sellerType?: string;
  sellerId?: string;
  sellerSnapshot?: {
    id?: string;
    name?: string;
    address?: string;
  };
  fulfillmentProviderSnapshot?: {
    provider?: string;
    restaurantName?: string;
  };
  legalTermsVersion?: string;
  privacyVersion?: string;
  cancellationPolicyVersion?: string;
  deliveryPinHash?: string;
  deliveryPinCiphertext?: string;
  deliveryPinCreatedAt?: string;
  deliveryPinExpiresAt?: string;
  deliveryPinVerifiedAt?: string;
  deliveryPinVerifiedBy?: string;
  deliveryPinAttemptCount?: number;
  deliveryPinLockedUntil?: string;
  deliveryVerificationMethod?:
    "customer_confirmation" | "not_required" | "pin" | "support_override";
  deliveryVerificationStatus?:
    "locked" | "not_required" | "overridden" | "pending" | "verified";
  deliveryVerificationEvidence?: string;
  authorizedRecipientName?: string;
  authorizedRecipientRelation?: string;
  authorizedThirdPartyDelivery?: boolean;
  refundStatus?:
    | "approved"
    | "failed"
    | "not_requested"
    | "partially_approved"
    | "processing"
    | "refunded"
    | "rejected"
    | "requested"
    | "under_review";
  refundRequestedAt?: string;
  refundRequestedBy?: string;
  refundReason?: string;
  refundAmount?: number;
  refundResolution?: string;
  refundResolvedAt?: string;
  refundResolvedBy?: string;
  stripeRefundId?: string;
  refundEvidence?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  subtotal?: number;
  shippingCost?: number;
  productsSubtotal?: number;
  shippingFee?: number;
  discount?: number;
  tax?: number;
  platformCommission?: number;
  stripeFee?: number;
  stripeNetAmount?: number;
  driverPayout?: number;
  grossTotal?: number;
  storeNetTotal?: number;
  platformNetTotal?: number;
  shippingAddress?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
  };
  codInstructions?: string;
  deliveryNotes?: string;
  repartidorAsignado?: RepartidorReference;
  repartidorAsignadoAt?: string;
  deliveryOfertaEnviada?: boolean;
  deliveryOfertaExpiresAt?: string;
  dispatchStatus?:
    | "accepted"
    | "at_door"
    | "completed"
    | "not_required"
    | "offered"
    | "waiting_for_driver";
  settlementStatus?: "cancelled" | "pending" | "ready" | "refunded" | "settled";
  cashCollectedBy?:
    "admin" | "community_driver" | "none" | "store_driver" | "store";
  driverType?: "community" | "none" | "store";
  offeredTo?: RepartidorReference;
  pickupStore?: AffiliateStoreReference;
  estimatedPickupDate?: string;
  pickupStatus?: "expired" | "in_transit" | "picked_up" | "ready_for_pickup";
  pickupCode?: string;
  affiliateStore?: AffiliateStoreReference;
  cancelledAt?: string;
  refundedAt?: string;
  settlementDate?: string;
  orderEvents?: Array<{
    type?: string;
    at?: string;
    actor?: string;
    source?: string;
    reason?: string;
    payloadJson?: string;
    _key: string;
  }>;
  isClickCollect: false | true;
  storeInfo: {
    storeName: string | null;
    storeAddress: string | null;
    storePhone: string | null;
  };
}>;

// Source: sanity/lib/products/getAllAffiliateStores.ts
// Variable: ALL_STORES_QUERY
// Query: *[_type == "affiliateStore" && isActive == true] | order(name asc) {            _id,            _type,            _createdAt,            _updatedAt,            _rev,            name,            storeId,            image,            coverImage,            storeCategories[]->{                _id,                title,                slug,                icon {                    type,                    emoji,                    image {                        asset->{                            _id,                            url                        },                        alt                    }                }            },            address,            coordinates,            contact,            operatingHours,            isActive,            isOpen,            manualOperationalStatus,            highDemandMode,            capacity,            averageDeliveryTime,            deliveryFee,            deliveryTimeMin,            deliveryTimeMax,            serviceTypes        }
export type ALL_STORES_QUERY_RESULT = Array<{
  _id: string;
  _type: "affiliateStore";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  storeId: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  storeCategories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    icon: {
      type: "emoji" | "image" | null;
      emoji: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
        alt: null;
      } | null;
    } | null;
  }> | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  coordinates: {
    latitude?: number;
    longitude?: number;
  } | null;
  contact: {
    phone?: string;
    email?: string;
    manager?: string;
  } | null;
  operatingHours: {
    monday?: string;
    tuesday?: string;
    wednesday?: string;
    thursday?: string;
    friday?: string;
    saturday?: string;
    sunday?: string;
  } | null;
  isActive: true;
  isOpen: boolean | null;
  manualOperationalStatus: "auto" | "closed" | "open" | null;
  highDemandMode: boolean | null;
  capacity: number | null;
  averageDeliveryTime: number | null;
  deliveryFee: number | null;
  deliveryTimeMin: number | null;
  deliveryTimeMax: number | null;
  serviceTypes: {
    delivery?: boolean;
    pickup?: boolean;
    deliveryRadius?: number;
    minimumOrderDelivery?: number;
    onDemand?: boolean;
    onDemandExtraMinutes?: number;
  } | null;
}>;

// Source: sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(name asc)
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
}>;

// Source: sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[           _type == "product"           && approvalStatus == "approved"           && isVisible != false        ] | order(name asc) {           ...,           affiliateStore->{               _id,               name,               storeId,               deliveryFee,               deliveryTimeMin,               deliveryTimeMax,               averageDeliveryTime           }        }
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  affiliateStore: {
    _id: string;
    name: string | null;
    storeId: string | null;
    deliveryFee: number | null;
    deliveryTimeMin: number | null;
    deliveryTimeMax: number | null;
    averageDeliveryTime: number | null;
  } | null;
  optionGroups?: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "multiple" | "single";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }>;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  approvalStatus?: "approved" | "pending" | "rejected";
  isVisible?: boolean;
  pendingChanges?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<{
      title?: string;
      description?: string;
      required?: boolean;
      selectionType?: string;
      options?: Array<{
        label?: string;
        description?: string;
        priceDelta?: number;
        isDefault?: boolean;
        _type: "option";
        _key: string;
      }>;
      _type: "optionGroup";
      _key: string;
    }>;
  };
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}>;

// Source: sanity/lib/products/getAllStoreCategories.ts
// Variable: ALL_STORE_CATEGORIES_QUERY
// Query: *[_type == "storeCategory"] | order(order asc, title asc) {      _id,      title,      slug,      description,      icon {        type,        emoji,        image {          asset->{            _id,            url          },          alt        }      },      order    }
export type ALL_STORE_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  icon: {
    type: "emoji" | "image" | null;
    emoji: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: null;
    } | null;
  } | null;
  order: number | null;
}>;

// Source: sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[            _type == "product"            && slug.current == $slug            && approvalStatus == "approved"            && isVisible != false        ] | order(name asc) [0]{          ...,          affiliateStore->{            _id,            name,            image,            averageDeliveryTime,            deliveryFee,            deliveryTimeMin,            deliveryTimeMax          },          optionGroups        }
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  affiliateStore: {
    _id: string;
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    averageDeliveryTime: number | null;
    deliveryFee: number | null;
    deliveryTimeMin: number | null;
    deliveryTimeMax: number | null;
  } | null;
  optionGroups: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "multiple" | "single";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }> | null;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  approvalStatus?: "approved" | "pending" | "rejected";
  isVisible?: boolean;
  pendingChanges?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<{
      title?: string;
      description?: string;
      required?: boolean;
      selectionType?: string;
      options?: Array<{
        label?: string;
        description?: string;
        priceDelta?: number;
        isDefault?: boolean;
        _type: "option";
        _key: string;
      }>;
      _type: "optionGroup";
      _key: string;
    }>;
  };
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
} | null;

// Source: sanity/lib/products/getProductsByCategory.tsx
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[            _type == "product"            && references(*[_type == "category" && slug.current == $categorySlug]._id)            && approvalStatus == "approved"            && isVisible != false            ] | order(name asc)
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  affiliateStore?: AffiliateStoreReference;
  optionGroups?: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "multiple" | "single";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }>;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  approvalStatus?: "approved" | "pending" | "rejected";
  isVisible?: boolean;
  pendingChanges?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<{
      title?: string;
      description?: string;
      required?: boolean;
      selectionType?: string;
      options?: Array<{
        label?: string;
        description?: string;
        priceDelta?: number;
        isDefault?: boolean;
        _type: "option";
        _key: string;
      }>;
      _type: "optionGroup";
      _key: string;
    }>;
  };
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}>;

// Source: sanity/lib/products/getProductsByStore.ts
// Variable: PRODUCTS_BY_STORE_QUERY
// Query: *[      _type == "product" &&      affiliateStore._ref == $storeId &&      approvalStatus == "approved" &&      isVisible != false    ] | order(name asc) {      _id,      _createdAt,      name,      slug,      image,      price,      stock,      approvalStatus,      isVisible,      description,      categories[]->{        _id,        title,        slug      },      optionGroups,      affiliateStore->{        _id,        name,        categories,        averageDeliveryTime,        deliveryFee,        deliveryTimeMin,        deliveryTimeMax      }    }
export type PRODUCTS_BY_STORE_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  price: number | null;
  stock: number | null;
  approvalStatus: "approved" | "pending" | "rejected" | null;
  isVisible: boolean | null;
  description: BlockContent | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  optionGroups: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "multiple" | "single";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }> | null;
  affiliateStore: {
    _id: string;
    name: string | null;
    categories: Array<{
      name?: string;
      slug?: Slug;
      order?: number;
      _key: string;
    }> | null;
    averageDeliveryTime: number | null;
    deliveryFee: number | null;
    deliveryTimeMin: number | null;
    deliveryTimeMax: number | null;
  } | null;
}>;

// Source: sanity/lib/products/getStoreById.ts
// Variable: STORE_BY_ID_QUERY
// Query: *[_type == "affiliateStore" && _id == $storeId][0] {      _id,      name,      storeId,      image,      coverImage,      categories,      address,      coordinates,      contact,      operatingHours,      isActive,      isOpen,      manualOperationalStatus,      highDemandMode,      capacity,      averageDeliveryTime,      deliveryFee,      deliveryTimeMin,      deliveryTimeMax,      serviceTypes    }
export type STORE_BY_ID_QUERY_RESULT = {
  _id: string;
  name: string | null;
  storeId: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categories: Array<{
    name?: string;
    slug?: Slug;
    order?: number;
    _key: string;
  }> | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  coordinates: {
    latitude?: number;
    longitude?: number;
  } | null;
  contact: {
    phone?: string;
    email?: string;
    manager?: string;
  } | null;
  operatingHours: {
    monday?: string;
    tuesday?: string;
    wednesday?: string;
    thursday?: string;
    friday?: string;
    saturday?: string;
    sunday?: string;
  } | null;
  isActive: boolean | null;
  isOpen: boolean | null;
  manualOperationalStatus: "auto" | "closed" | "open" | null;
  highDemandMode: boolean | null;
  capacity: number | null;
  averageDeliveryTime: number | null;
  deliveryFee: number | null;
  deliveryTimeMin: number | null;
  deliveryTimeMax: number | null;
  serviceTypes: {
    delivery?: boolean;
    pickup?: boolean;
    deliveryRadius?: number;
    minimumOrderDelivery?: number;
    onDemand?: boolean;
    onDemandExtraMinutes?: number;
  } | null;
} | null;

// Source: sanity/lib/products/searchProductsByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[        _type == "product"        && name match $searchParam        && approvalStatus == "approved"        && isVisible != false     ] | order(name asc)    {      ...,      affiliateStore->{ _id, name }    }
export type PRODUCT_SEARCH_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  affiliateStore: {
    _id: string;
    name: string | null;
  } | null;
  optionGroups?: Array<{
    title?: string;
    description?: string;
    required?: boolean;
    selectionType?: "multiple" | "single";
    options?: Array<{
      label?: string;
      description?: string;
      priceDelta?: number;
      isDefault?: boolean;
      _type: "option";
      _key: string;
    }>;
    _type: "optionGroup";
    _key: string;
  }>;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  approvalStatus?: "approved" | "pending" | "rejected";
  isVisible?: boolean;
  pendingChanges?: {
    name?: string;
    price?: number;
    stock?: number;
    description?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    categories?: Array<
      {
        _key: string;
      } & CategoryReference
    >;
    optionGroups?: Array<{
      title?: string;
      description?: string;
      required?: boolean;
      selectionType?: string;
      options?: Array<{
        label?: string;
        description?: string;
        priceDelta?: number;
        isDefault?: boolean;
        _type: "option";
        _key: string;
      }>;
      _type: "optionGroup";
      _key: string;
    }>;
  };
  submittedBy?: string;
  submittedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}>;

// Source: sanity/lib/promotions/getActivePromoBanners.ts
// Variable: ACTIVE_PROMO_BANNERS_QUERY
// Query: *[    _type == "promoBanner"    && isActive == true    && (!defined(validFrom) || validFrom <= now())    && (!defined(validUntil) || validUntil >= now())  ] | order(sortOrder asc, _createdAt desc) {    _id,    title,    description,    bannerType,    mainColor,    desktopImage,    mobileImage,    sortOrder,    displayDurationSeconds,    ctaText,    ctaLink,    affiliateStore-> {      _id,      name,      image    },    "sale": select(      defined(sale)      && sale->isActive == true      && (!defined(sale->validFrom) || sale->validFrom <= now())      && (!defined(sale->validUntil) || sale->validUntil >= now()) => sale->{        _id,        title,        description,        discountAmount,        discountType,        couponCode      },      null    )  }
export type ACTIVE_PROMO_BANNERS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  bannerType:
    | "announcement"
    | "event"
    | "featured"
    | "info"
    | "promotion"
    | "warning"
    | null;
  mainColor:
    | "#000000"
    | "#09193B"
    | "#0F766E"
    | "#111827"
    | "#166534"
    | "#6D28D9"
    | "#850C22"
    | "#C2410C"
    | "#FFFFFF"
    | null;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  sortOrder: number | null;
  displayDurationSeconds: number | null;
  ctaText: string | null;
  ctaLink: string | null;
  affiliateStore: {
    _id: string;
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  sale: {
    _id: string;
    title: string | null;
    description: string | null;
    discountAmount: number | null;
    discountType: "fixed_amount" | "percentage" | null;
    couponCode: string | null;
  } | null;
}>;

// Source: sanity/lib/sales/getActiveSaleByCouponCode.ts
// Variable: ACTIVE_SALE_BY_COUPON_QUERY
// Query: *[            _type == "sale"            && isActive == true             && couponCode == $couponCode        ] | order(validFrom desc)[0]
export type ACTIVE_SALE_BY_COUPON_QUERY_RESULT = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  discountType?: "fixed_amount" | "percentage";
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  stripePromotionCodeId?: string;
  autoApply?: boolean;
  allowedOrderTypes?: Array<string>;
  allowedPaymentMethods?: Array<string>;
  allowedStores?: Array<
    {
      _key: string;
    } & AffiliateStoreReference
  >;
  isActive?: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {\n      ...,\n      "isClickCollect": orderType == "pickup",\n      "storeInfo": select(\n        orderType == "pickup" => {\n          "storeName": pickupStore->name,\n          "storeAddress": pickupStore->address.street,\n          "storePhone": pickupStore->contact.phone\n        }\n      ),\n      products[]{\n        ...,\n        product->\n      }\n    }\n ': MY_ORDERS_QUERY_RESULT;
    '\n        *[_type == "affiliateStore" && isActive == true] | order(name asc) {\n            _id,\n            _type,\n            _createdAt,\n            _updatedAt,\n            _rev,\n            name,\n            storeId,\n            image,\n            coverImage,\n            storeCategories[]->{\n                _id,\n                title,\n                slug,\n                icon {\n                    type,\n                    emoji,\n                    image {\n                        asset->{\n                            _id,\n                            url\n                        },\n                        alt\n                    }\n                }\n            },\n            address,\n            coordinates,\n            contact,\n            operatingHours,\n            isActive,\n            isOpen,\n            manualOperationalStatus,\n            highDemandMode,\n            capacity,\n            averageDeliveryTime,\n            deliveryFee,\n            deliveryTimeMin,\n            deliveryTimeMax,\n            serviceTypes\n        }\n    ': ALL_STORES_QUERY_RESULT;
    '\n        *[_type == "category"] | order(name asc)\n        ': ALL_CATEGORIES_QUERY_RESULT;
    '\n       *[\n           _type == "product"\n           && approvalStatus == "approved"\n           && isVisible != false\n        ] | order(name asc) {\n           ...,\n           affiliateStore->{\n               _id,\n               name,\n               storeId,\n               deliveryFee,\n               deliveryTimeMin,\n               deliveryTimeMax,\n               averageDeliveryTime\n           }\n        }\n    ': ALL_PRODUCTS_QUERY_RESULT;
    '\n    *[_type == "storeCategory"] | order(order asc, title asc) {\n      _id,\n      title,\n      slug,\n      description,\n      icon {\n        type,\n        emoji,\n        image {\n          asset->{\n            _id,\n            url\n          },\n          alt\n        }\n      },\n      order\n    }\n  ': ALL_STORE_CATEGORIES_QUERY_RESULT;
    '\n        *[\n            _type == "product"\n            && slug.current == $slug\n            && approvalStatus == "approved"\n            && isVisible != false\n        ] | order(name asc) [0]{\n          ...,\n          affiliateStore->{\n            _id,\n            name,\n            image,\n            averageDeliveryTime,\n            deliveryFee,\n            deliveryTimeMin,\n            deliveryTimeMax\n          },\n          optionGroups\n        }\n        ': PRODUCT_BY_ID_QUERY_RESULT;
    '\n        *[\n            _type == "product"\n            && references(*[_type == "category" && slug.current == $categorySlug]._id)\n            && approvalStatus == "approved"\n            && isVisible != false\n            ] | order(name asc)\n        ': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '\n    *[\n      _type == "product" &&\n      affiliateStore._ref == $storeId &&\n      approvalStatus == "approved" &&\n      isVisible != false\n    ] | order(name asc) {\n      _id,\n      _createdAt,\n      name,\n      slug,\n      image,\n      price,\n      stock,\n      approvalStatus,\n      isVisible,\n      description,\n      categories[]->{\n        _id,\n        title,\n        slug\n      },\n      optionGroups,\n      affiliateStore->{\n        _id,\n        name,\n        categories,\n        averageDeliveryTime,\n        deliveryFee,\n        deliveryTimeMin,\n        deliveryTimeMax\n      }\n    }\n  ': PRODUCTS_BY_STORE_QUERY_RESULT;
    '\n    *[_type == "affiliateStore" && _id == $storeId][0] {\n      _id,\n      name,\n      storeId,\n      image,\n      coverImage,\n      categories,\n      address,\n      coordinates,\n      contact,\n      operatingHours,\n      isActive,\n      isOpen,\n      manualOperationalStatus,\n      highDemandMode,\n      capacity,\n      averageDeliveryTime,\n      deliveryFee,\n      deliveryTimeMin,\n      deliveryTimeMax,\n      serviceTypes\n    }\n  ': STORE_BY_ID_QUERY_RESULT;
    '\n     *[\n        _type == "product"\n        && name match $searchParam\n        && approvalStatus == "approved"\n        && isVisible != false\n     ] | order(name asc)\n    {\n      ...,\n      affiliateStore->{ _id, name }\n    }\n    ': PRODUCT_SEARCH_QUERY_RESULT;
    '\n  *[\n    _type == "promoBanner"\n    && isActive == true\n    && (!defined(validFrom) || validFrom <= now())\n    && (!defined(validUntil) || validUntil >= now())\n  ] | order(sortOrder asc, _createdAt desc) {\n    _id,\n    title,\n    description,\n    bannerType,\n    mainColor,\n    desktopImage,\n    mobileImage,\n    sortOrder,\n    displayDurationSeconds,\n    ctaText,\n    ctaLink,\n    affiliateStore-> {\n      _id,\n      name,\n      image\n    },\n\n    "sale": select(\n      defined(sale)\n      && sale->isActive == true\n      && (!defined(sale->validFrom) || sale->validFrom <= now())\n      && (!defined(sale->validUntil) || sale->validUntil >= now()) => sale->{\n        _id,\n        title,\n        description,\n        discountAmount,\n        discountType,\n        couponCode\n      },\n      null\n    )\n  }\n': ACTIVE_PROMO_BANNERS_QUERY_RESULT;
    '\n        *[\n            _type == "sale"\n            && isActive == true \n            && couponCode == $couponCode\n        ] | order(validFrom desc)[0]\n        ': ACTIVE_SALE_BY_COUPON_QUERY_RESULT;
  }
}
