import { BasketIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export const orderType = defineType({
  name: "order",
  title: "Order",
  type: "document",
  icon: BasketIcon,
  fields: [
    defineField({ name: "orderNumber", title: "Order Number", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "stripeCheckoutSessionId", title: "Stripe Checkout Session ID", type: "string" }),
    defineField({ name: "baserowRowId", title: "Baserow Row ID", type: "number", readOnly: true }),
    defineField({ name: "baserowSyncStatus", title: "Baserow Sync Status", type: "string", readOnly: true }),
    defineField({ name: "baserowSyncedAt", title: "Baserow Synced At", type: "datetime", readOnly: true }),
    defineField({ name: "baserowSyncError", title: "Baserow Sync Error", type: "text", readOnly: true }),
    defineField({ name: "stripeCustomerId", title: "Stripe Customer ID", type: "string", description: "Required for Stripe payments, optional for COD orders" }),
    defineField({ name: "clerkUserId", title: "Store User ID", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "customerName", title: "Customer Name", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "email", title: "Customer Email", type: "string", validation: (Rule) => Rule.required().email() }),
    defineField({ name: "phone", title: "Customer Phone", type: "string", description: "Customer phone number for delivery and order updates" }),
    defineField({
      name: "orderType",
      title: "Order Type",
      type: "string",
      options: { list: [{ title: "Delivery", value: "delivery" }, { title: "Pickup", value: "pickup" }] },
      initialValue: "delivery",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "paymentMethod",
      title: "Payment Method",
      type: "string",
      options: {
        list: [
          { title: "Stripe", value: "stripe" },
          { title: "Cash on Delivery", value: "cash_on_delivery" },
          { title: "Cash at Store", value: "cash_at_store" },
          { title: "Card at Store", value: "card_at_store" },
          { title: "Manual", value: "manual" },
          { title: "Bank Transfer SPEI", value: "bank_transfer" },
          { title: "OXXO", value: "oxxo" },
          { title: "Legacy Card", value: "card" },
          { title: "Legacy Cash on Pickup", value: "cash_on_pickup" },
          { title: "Legacy Card on Pickup", value: "card_on_pickup" },
        ],
      },
      description: "Method used for payment",
    }),
    defineField({
      name: "paymentProvider",
      title: "Payment Provider",
      type: "string",
      options: { list: [{ title: "Stripe", value: "stripe" }, { title: "Cash", value: "cash" }, { title: "External POS", value: "external_pos" }, { title: "None", value: "none" }] },
    }),
    defineField({ name: "paidOnline", title: "Paid Online", type: "boolean" }),
    defineField({ name: "requiresStripeReconciliation", title: "Requires Stripe Reconciliation", type: "boolean" }),
    defineField({ name: "stripePaymentIntentId", title: "Stripe Payment Intent ID", type: "string", description: "Required for Stripe payments, optional for COD orders" }),
    defineField({
      name: "products",
      title: "Products",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "product", title: "Product Bought", type: "reference", to: [{ type: "product" }] }),
            defineField({ name: "quantity", title: "Quantity Purchased", type: "number" }),
            defineField({
              name: "customizations",
              title: "Customization Options",
              type: "array",
              of: [
                defineArrayMember({
                  type: "object",
                  fields: [
                    defineField({ name: "title", title: "Option Group Title", type: "string" }),
                    defineField({
                      name: "options",
                      title: "Selected Options",
                      type: "array",
                      of: [
                        defineArrayMember({
                          type: "object",
                          fields: [
                            defineField({ name: "label", title: "Option Label", type: "string" }),
                            defineField({ name: "priceDelta", title: "Price Delta", type: "number" }),
                          ],
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
            defineField({ name: "notes", title: "Item Notes", type: "text" }),
          ],
          preview: {
            select: { product: "product.name", quantity: "quantity", image: "product.image", price: "product.price", currency: "product.currency" },
            prepare(select) {
              return {
                title: `${select.product} x ${select.quantity}`,
                subtitle: `${(select.price ?? 0) * (select.quantity ?? 0)} ${select.currency ?? ""}`,
                media: select.image,
              };
            },
          },
        }),
      ],
    }),
    defineField({ name: "totalPrice", title: "Total Price", type: "number", validation: (Rule) => Rule.required().min(0) }),
    defineField({ name: "currency", title: "Currency", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "amountDiscount", title: "Amount Discount", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({
      name: "status",
      title: "Legacy Status",
      type: "string",
      options: { list: [{ title: "Pending", value: "pending" }, { title: "Paid", value: "paid" }, { title: "Failed", value: "failed" }, { title: "Expired", value: "expired" }, { title: "Pending Delivery", value: "pending_delivery" }, { title: "Pending Pickup", value: "pending_pickup" }, { title: "Shipped", value: "shipped" }, { title: "Delivered", value: "delivered" }, { title: "Cancelled", value: "cancelled" }, { title: "Ready for Pickup", value: "ready_for_pickup" }, { title: "Picked Up", value: "picked_up" }, { title: "Completed", value: "completed" }] },
      description: "Compatibilidad temporal para UI antigua.",
    }),
    defineField({ name: "orderStatus", title: "Order Status", type: "string", initialValue: "pending", options: { list: [{ title: "Pending", value: "pending" }, { title: "Processing", value: "processing" }, { title: "Shipped", value: "shipped" }, { title: "Delivered", value: "delivered" }, { title: "Cancelled", value: "cancelled" }, { title: "Ready for Pickup", value: "ready_for_pickup" }, { title: "Picked Up", value: "picked_up" }, { title: "Completed", value: "completed" }] } }),
    defineField({ name: "paymentStatus", title: "Payment Status", type: "string", initialValue: "pending", options: { list: [{ title: "Pending", value: "pending" }, { title: "Paid", value: "paid" }, { title: "Failed", value: "failed" }, { title: "Expired", value: "expired" }, { title: "Unpaid", value: "unpaid" }, { title: "Refunded", value: "refunded" }, { title: "Requires Refund", value: "requires_refund" }] } }),
    defineField({ name: "expiredAt", title: "Expired At", type: "datetime" }),
    defineField({ name: "paidAt", title: "Paid At", type: "datetime" }),
    defineField({ name: "bankTransferReference", title: "Bank Transfer Reference", type: "string" }),
    defineField({ name: "bankTransferClabe", title: "Bank Transfer CLABE", type: "string" }),
    defineField({ name: "oxxoReference", title: "OXXO Reference Number", type: "string" }),
    defineField({ name: "orderDate", title: "Order Date", type: "datetime", validation: (Rule) => Rule.required() }),
    defineField({ name: "fulfillmentProvider", title: "Responsable de entrega", type: "string", options: { list: ["pickup", "restaurant_delivery", "elmenu_delivery", "third_party_logistics"] } }),
    defineField({ name: "sellerType", title: "Tipo de vendedor", type: "string", initialValue: "restaurant" }),
    defineField({ name: "sellerId", title: "ID del vendedor", type: "string" }),
    defineField({ name: "sellerSnapshot", title: "Snapshot del vendedor", type: "object", fields: [
      defineField({ name: "id", title: "ID", type: "string" }),
      defineField({ name: "name", title: "Nombre", type: "string" }),
      defineField({ name: "address", title: "Dirección", type: "string" }),
    ] }),
    defineField({ name: "fulfillmentProviderSnapshot", title: "Snapshot de entrega", type: "object", fields: [
      defineField({ name: "provider", title: "Proveedor", type: "string" }),
      defineField({ name: "restaurantName", title: "Restaurante", type: "string" }),
    ] }),
    defineField({ name: "legalTermsVersion", title: "Versión de términos", type: "string" }),
    defineField({ name: "privacyVersion", title: "Versión de privacidad", type: "string" }),
    defineField({ name: "cancellationPolicyVersion", title: "Versión de cancelaciones", type: "string" }),
    defineField({ name: "deliveryPinHash", title: "Hash PIN entrega", type: "string", hidden: true, readOnly: true }),
    defineField({ name: "deliveryPinCiphertext", title: "PIN cifrado", type: "string", hidden: true, readOnly: true }),
    defineField({ name: "deliveryPinCreatedAt", title: "PIN creado", type: "datetime", readOnly: true }),
    defineField({ name: "deliveryPinExpiresAt", title: "PIN expira", type: "datetime", readOnly: true }),
    defineField({ name: "deliveryPinVerifiedAt", title: "PIN verificado", type: "datetime", readOnly: true }),
    defineField({ name: "deliveryPinVerifiedBy", title: "PIN verificado por", type: "string", readOnly: true }),
    defineField({ name: "deliveryPinAttemptCount", title: "Intentos PIN", type: "number", readOnly: true }),
    defineField({ name: "deliveryPinLockedUntil", title: "PIN bloqueado hasta", type: "datetime", readOnly: true }),
    defineField({ name: "deliveryVerificationMethod", title: "Método de verificación", type: "string", options: { list: ["pin", "customer_confirmation", "support_override", "not_required"] } }),
    defineField({ name: "deliveryVerificationStatus", title: "Estado de verificación", type: "string", options: { list: ["pending", "verified", "locked", "overridden", "not_required"] } }),
    defineField({ name: "deliveryVerificationEvidence", title: "Evidencia de entrega", type: "text" }),
    defineField({ name: "authorizedRecipientName", title: "Persona autorizada", type: "string" }),
    defineField({ name: "authorizedRecipientRelation", title: "Relación", type: "string" }),
    defineField({ name: "authorizedThirdPartyDelivery", title: "Entrega a tercero autorizada", type: "boolean" }),
    defineField({ name: "refundStatus", title: "Estado de reembolso", type: "string", initialValue: "not_requested", options: { list: ["not_requested", "requested", "under_review", "approved", "partially_approved", "rejected", "processing", "refunded", "failed"] } }),
    defineField({ name: "refundRequestedAt", title: "Reembolso solicitado", type: "datetime" }),
    defineField({ name: "refundRequestedBy", title: "Solicitado por", type: "string" }),
    defineField({ name: "refundReason", title: "Motivo de reembolso", type: "text" }),
    defineField({ name: "refundAmount", title: "Monto de reembolso", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "refundResolution", title: "Resolución", type: "text" }),
    defineField({ name: "refundResolvedAt", title: "Resuelto", type: "datetime" }),
    defineField({ name: "refundResolvedBy", title: "Resuelto por", type: "string" }),
    defineField({ name: "stripeRefundId", title: "Stripe Refund ID", type: "string" }),
    defineField({ name: "refundEvidence", title: "Evidencia de reembolso", type: "array", of: [{ type: "file" }] }),
    defineField({ name: "subtotal", title: "Subtotal", type: "number", description: "Legacy subtotal before shipping and taxes" }),
    defineField({ name: "shippingCost", title: "Shipping Cost", type: "number", description: "Legacy shipping cost" }),
    defineField({ name: "productsSubtotal", title: "Products Subtotal", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "shippingFee", title: "Shipping Fee", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "discount", title: "Discount", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "tax", title: "Tax", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "platformCommission", title: "Platform Commission", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "stripeFee", title: "Stripe Fee", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "stripeNetAmount", title: "Stripe Net Amount", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "driverPayout", title: "Driver Payout", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "grossTotal", title: "Gross Total", type: "number", validation: (Rule) => Rule.min(0) }),
    defineField({ name: "storeNetTotal", title: "Store Net Total", type: "number" }),
    defineField({ name: "platformNetTotal", title: "Platform Net Total", type: "number" }),
    defineField({
      name: "shippingAddress",
      title: "Shipping Address",
      type: "object",
      fields: [
        defineField({ name: "line1", title: "Address Line 1", type: "string" }),
        defineField({ name: "line2", title: "Address Line 2", type: "string" }),
        defineField({ name: "city", title: "City", type: "string" }),
        defineField({ name: "state", title: "State", type: "string" }),
        defineField({ name: "postal_code", title: "Postal Code", type: "string" }),
        defineField({ name: "country", title: "Country", type: "string" }),
        defineField({ name: "latitude", title: "Latitude", type: "number" }),
        defineField({ name: "longitude", title: "Longitude", type: "number" }),
      ],
    }),
    defineField({ name: "codInstructions", title: "Cash on Delivery Instructions", type: "text" }),
    defineField({ name: "deliveryNotes", title: "Delivery Notes", type: "text" }),
    defineField({ name: "repartidorAsignado", title: "Assigned Driver", type: "reference", to: [{ type: "repartidor" }] }),
    defineField({ name: "repartidorAsignadoAt", title: "Assigned Driver At", type: "datetime" }),
    defineField({ name: "deliveryOfertaEnviada", title: "Delivery Offer Sent", type: "boolean", initialValue: false }),
    defineField({ name: "deliveryOfertaExpiresAt", title: "Delivery Offer Expires At", type: "datetime" }),
    defineField({ name: "dispatchStatus", title: "Dispatch Status", type: "string", initialValue: "waiting_for_driver", options: { list: [{ title: "Not Required", value: "not_required" }, { title: "Waiting for Driver", value: "waiting_for_driver" }, { title: "Offered", value: "offered" }, { title: "Accepted", value: "accepted" }, { title: "At Door", value: "at_door" }, { title: "Completed", value: "completed" }] } }),
    defineField({ name: "settlementStatus", title: "Settlement Status", type: "string", initialValue: "pending", options: { list: [{ title: "Pending", value: "pending" }, { title: "Ready", value: "ready" }, { title: "Settled", value: "settled" }, { title: "Cancelled", value: "cancelled" }, { title: "Refunded", value: "refunded" }] } }),
    defineField({
      name: "cashCollectedBy",
      title: "Cash Collected By",
      type: "string",
      options: { list: [{ title: "Store", value: "store" }, { title: "Community Driver", value: "community_driver" }, { title: "Store Driver", value: "store_driver" }, { title: "Admin", value: "admin" }, { title: "None", value: "none" }] },
    }),
    defineField({ name: "driverType", title: "Driver Type", type: "string", options: { list: [{ title: "Store", value: "store" }, { title: "Community", value: "community" }, { title: "None", value: "none" }] } }),
    defineField({ name: "offeredTo", title: "Offer sent to", type: "reference", to: [{ type: "repartidor" }] }),
    defineField({ name: "pickupStore", title: "Pickup Store", type: "reference", to: [{ type: "affiliateStore" }], hidden: ({ document }) => document?.orderType !== "pickup" }),
    defineField({ name: "estimatedPickupDate", title: "Estimated Pickup Date", type: "datetime", hidden: ({ document }) => document?.orderType !== "pickup" }),
    defineField({ name: "pickupStatus", title: "Pickup Status", type: "string", options: { list: [{ title: "In Transit", value: "in_transit" }, { title: "Ready for Pickup", value: "ready_for_pickup" }, { title: "Picked Up", value: "picked_up" }, { title: "Expired", value: "expired" }] }, hidden: ({ document }) => document?.orderType !== "pickup" }),
    defineField({ name: "pickupCode", title: "Pickup Code", type: "string", hidden: ({ document }) => document?.orderType !== "pickup" }),
    defineField({ name: "affiliateStore", title: "Store / Restaurant", type: "reference", to: [{ type: "affiliateStore" }] }),
    defineField({ name: "cancelledAt", title: "Cancelled At", type: "datetime" }),
    defineField({ name: "refundedAt", title: "Refunded At", type: "datetime" }),
    defineField({ name: "settlementDate", title: "Settlement Date", type: "datetime" }),
    defineField({
      name: "orderEvents",
      title: "Order Events",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "type", title: "Type", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "at", title: "At", type: "datetime", validation: (Rule) => Rule.required() }),
            defineField({ name: "actor", title: "Actor", type: "string" }),
            defineField({ name: "source", title: "Source", type: "string" }),
            defineField({ name: "reason", title: "Reason", type: "string" }),
            defineField({ name: "payloadJson", title: "Payload JSON", type: "text" }),
          ],
        }),
      ],
    }),
  ],
  preview: {
    select: { name: "customerName", amount: "grossTotal", fallbackAmount: "totalPrice", currency: "currency", orderId: "orderNumber", email: "email", orderType: "orderType" },
    prepare(select) {
      const orderIdSnippet = select.orderId ? `${select.orderId.slice(0, 5)}...${select.orderId.slice(-5)}` : "sin numero";
      const typeBadge = select.orderType === "pickup" ? "Pickup" : "Delivery";
      const amount = select.amount ?? select.fallbackAmount ?? 0;
      return {
        title: `${typeBadge} - ${select.name} (${orderIdSnippet})`,
        subtitle: `${amount} ${select.currency ?? "mxn"}, ${select.email}`,
        media: BasketIcon,
      };
    },
  },
});

