import { defineField, defineType } from "sanity";

export const repartidorType = defineType({
  name: "repartidor",
  title: "Repartidor",
  type: "document",
  fields: [
    defineField({
      name: "nombre",
      title: "Nombre",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "telefono",
      title: "Telefono",
      type: "string",
      description: "Numero con codigo de pais",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tiendaAsignada",
      title: "Tienda Asignada",
      type: "reference",
      to: [{ type: "affiliateStore" }],
      description: "Tienda especifica a la que pertenece el repartidor",
    }),
    defineField({
      name: "activo",
      title: "Activo",
      type: "boolean",
      initialValue: true,
      description: "Permite activar o desactivar el repartidor sin eliminarlo",
    }),
    defineField({
      name: "disponible",
      title: "Disponible",
      type: "boolean",
      initialValue: false,
      description: "Si el repartidor está en servicio ahora mismo",
    }),
    defineField({
      name: "disponibleDesde",
      title: "Disponible Desde",
      type: "datetime",
      description: "Cuándo se conectó al servicio",
    }),
    defineField({
      name: "disponibleHasta",
      title: "Disponible Hasta",
      type: "datetime",
      description: "Cuándo termina la sesión de disponibilidad actual",
    }),
    defineField({
      name: "duracionDisponibilidadMinutos",
      title: "Duración de Disponibilidad (Minutos)",
      type: "number",
      description: "Duración total de la sesión vigente en minutos",
    }),
    defineField({
      name: "estadoDisponibilidad",
      title: "Estado de Disponibilidad",
      type: "string",
      initialValue: "offline",
      options: {
        list: [
          { title: "Disponible", value: "available" },
          { title: "Desconectado", value: "offline" },
          { title: "Ocupado", value: "busy" },
          { title: "Oferta Pendiente", value: "offer_pending" },
        ],
      },
      description: "Estado operativo actual del repartidor",
    }),
    defineField({
      name: "ultimaActividad",
      title: "Última Actividad",
      type: "datetime",
      description: "Última vez que interactuó con el bot",
    }),
    defineField({
      name: "pendienteConfirmacion",
      title: "Pendiente de Confirmación",
      type: "boolean",
      initialValue: false,
      description: "Se le mandó recordatorio y no ha respondido aún",
    }),
    defineField({
      name: "confirmacionEnviadaAt",
      title: "Confirmación Enviada At",
      type: "datetime",
      description: "Cuándo se mandó el recordatorio de confirmación",
    }),
    defineField({
      name: "esperandoSeleccionDisponibilidad",
      title: "Esperando Selección de Disponibilidad",
      type: "boolean",
      initialValue: false,
      description: "Indica si el repartidor debe elegir la duración de su sesión",
    }),
    defineField({
      name: "extensionPendiente",
      title: "Extensión Pendiente",
      type: "boolean",
      initialValue: false,
      description: "Indica si se le preguntó si desea extender su sesión",
    }),
    defineField({
      name: "extensionPreguntadaAt",
      title: "Extensión Preguntada At",
      type: "datetime",
      description: "Cuándo se envió la pregunta para extender la sesión",
    }),
    defineField({
      name: "autoDesconectadoAt",
      title: "Auto Desconectado At",
      type: "datetime",
      description: "Cuándo se desconectó automáticamente por fin de sesión",
    }),
    defineField({
      name: "motivoDesconexion",
      title: "Motivo de Desconexión",
      type: "string",
      description: "Motivo por el que quedó fuera de línea",
    }),
    defineField({
      name: "ultimoPedidoOfertado",
      title: "Último Pedido Ofertado",
      type: "reference",
      to: [{ type: "order" }],
      description: "El último pedido que se le envió al repartidor como oferta",
    }),
    defineField({
      name: "ofertaTipo",
      title: "Tipo de Oferta",
      type: "string",
      options: {
        list: [
          { title: "Individual", value: "single" },
          { title: "Bundle", value: "bundle" },
        ],
      },
      description: "Tipo de oferta activa enviada por WhatsApp",
    }),
    defineField({
      name: "pedidosOfertados",
      title: "Pedidos Ofertados",
      type: "array",
      of: [{ type: "reference", to: [{ type: "order" }] }],
      validation: (Rule) => Rule.max(2),
      description: "Pedidos incluidos en la oferta activa",
    }),
    defineField({
      name: "restauranteOferta",
      title: "Restaurante de la Oferta",
      type: "reference",
      to: [{ type: "affiliateStore" }],
      description: "Restaurante al que pertenece la oferta activa",
    }),
    defineField({
      name: "ofertaEnviadaAt",
      title: "Oferta Enviada At",
      type: "datetime",
      description: "Momento en que se envió la oferta actual",
    }),
    defineField({
      name: "ofertaExpiraAt",
      title: "Oferta Expira At",
      type: "datetime",
      description: "Momento en que expira la oferta actual",
    }),
    defineField({
      name: "notas",
      title: "Notas",
      type: "text",
      description: "Notas internas sobre el repartidor",
    }),
    defineField({
      name: "soporteChat",
      title: "Mensajes de soporte (Dispatch Center)",
      type: "array",
      of: [
        {
          type: "object",
          name: "mensajeSoporte",
          fields: [
            {
              name: "role",
              title: "Rol",
              type: "string",
              options: {
                list: [
                  { title: "Repartidor", value: "driver" },
                  { title: "Admin", value: "admin" },
                ],
              },
            },
            { name: "body", title: "Mensaje", type: "text" },
            { name: "createdAt", title: "Creado", type: "datetime" },
            { name: "readAt", title: "Leído por el operador", type: "datetime" },
          ],
        },
      ],
      description: "Conversación de soporte entre el repartidor (WhatsApp) y el Dispatch Center",
    }),
    defineField({ name: "soporteConversacionAbierta", title: "Conversación de soporte abierta", type: "boolean", readOnly: true, hidden: true }),
    defineField({
      name: "bloqueado",
      title: "Bloqueado",
      type: "boolean",
      initialValue: false,
      description: "Bloqueado por el Dispatch Center: no recibe ofertas ni asignaciones",
    }),
    defineField({
      name: "prioridad",
      title: "Prioridad de asignación",
      type: "number",
      initialValue: 0,
      description: "Mayor valor = se le asigna antes (0 = normal)",
    }),
    defineField({
      name: "foto",
      title: "Foto",
      type: "image",
      options: { hotspot: true },
      description: "Foto del repartidor para el Dispatch Center",
    }),
    defineField({
      name: "calificacion",
      title: "Calificación",
      type: "number",
      initialValue: 5,
      validation: (Rule) => Rule.min(0).max(5),
      description: "Calificación promedio (0 a 5)",
    }),
    defineField({
      name: "ultimaUbicacion",
      title: "Última ubicación",
      type: "object",
      fields: [
        { name: "lat", title: "Latitud", type: "number" },
        { name: "lng", title: "Longitud", type: "number" },
        { name: "reportedAt", title: "Reportada", type: "datetime" },
      ],
      description: "Última posición GPS conocida (opcional; aún no se reporta en el app)",
    }),
    defineField({
      name: "bateria",
      title: "Batería (%)",
      type: "number",
      validation: (Rule) => Rule.min(0).max(100),
      description: "Nivel de batería reportado por el teléfono (opcional)",
    }),
  ],
});


